### ISSUE TITLE
Apply Compound to Element Call, factoring in UX enhancements

### ISSUE THREAD

**Issue by rufuskahler** [vector-im/element-call#1235]
Update the Element Call designs to use & push forward Compound. Address visual & UX enhancements, ensuring they're accounted for in the designs:

```[tasklist]
### Tasks
- [x] Adopt Compound colour styles, typography styles & common Compound Web components
- [ ] https://github.com/vector-im/element-call/issues/1203
- [ ] https://github.com/vector-im/element-call/issues/1205
- [ ] https://github.com/vector-im/element-call/issues/1210
- [ ] https://github.com/vector-im/element-call/issues/1157
- [ ] https://github.com/vector-im/element-call/issues/1154
- [ ] Validate designs with @janogarcia, formalising new styles, components & iconography where necessary
- [ ] Move components from the Element Call & Trust & Decoration projects to the [Compound Web](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=130%3A6421&mode=design&t=cJMyg9cYJr7rzbaG-1) Figma
- [ ] Validate Compound Web components with @germain-gg, filling in any gaps to starting development
```

**Comment by fkwp** [comment]
This is predating our move to LiveKit. Please reopen if that is still an issue
