### ISSUE TITLE
EPIC Push-to-Talk

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#301]
This is an epic issue. List of individual issues is below:

- [x] This will be a separate Element call mode, enabled in the call settings, with a slightly different UI (https://github.com/vector-im/element-call/issues/300).
- [x] Users join a call muted, and must unmute to speak (https://github.com/vector-im/element-call/issues/294).
- [x] In this call type, video will be permanently disabled and there will be no video on/off button, to simplify the UI (https://github.com/vector-im/element-call/issues/295).
  - There is no toggle button to toggle mute/unmute on/off permanently.
  - Users can only unmute temporarily by pressing and holding the microphone/mute button or an external key.
- [x] Only one user can transmit (i.e. be unmuted) at once. Users who try to unmute while another user is speaking will get an audible ‘fail’ tone (https://github.com/vector-im/element-call/issues/298, https://github.com/vector-im/element-call/issues/299).
- [x] When a user presses the transmit button, there will be a fraction of a second’s pause and a beep, and then they are clear to transmit. (https://github.com/vector-im/element-call/issues/296)
- [x] When they release the button, there will be another beep. (https://github.com/vector-im/element-call/issues/296)
- [x] The maximum period for un-muting can be limited, e.g. to 20s (https://github.com/vector-im/element-call/issues/297).
- This includes the ability to transmit pressel clicks by briefly pressing the transmit button.
- Administrators will have the ability to remotely mute other users.
- [x] https://github.com/vector-im/element-call/issues/331

**Comment by compgeniuses** [comment]
This would be a fantastic addition into the product and Project.
I am also curious, is this element call, the one implemented inside element web

**Comment by jakewb-b** [comment]
Thanks! We're excited to get it working.

>I am also curious, is this element call, the one implemented inside element web

Element Call (call.element.io) is a new standalone web application, which we plan to integrate into Element Web and the other clients in the near future. 
Currently in the clients we have Matrix Native calling for 1:1 calls, and Jitsi for 1:many. Element Call should eventually be able to replace both.

**Comment by dbkr** [comment]
We're considering this feature-complete now, so closing this issue
