### ISSUE TITLE
Element Call integration into Mainline Apps

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#407]
This is an epic issue. List of individual issues is below:

## Highlevel Overview
This epic lists the tickets to integrate Element Call (which is based on WebRTC) into the mainline applications Element Web, Element Android, and Element iOS. 

Recent web-browser engines comprise a decent WebRTC implementation as well as (audio / video) media handling. On top of that stack Element Call was developed implementing scalable decentralised E2EE group voice and video calling ([MSC3401](https://github.com/matrix-org/matrix-doc/blob/matthew/group-voip/proposals/3401-group-voip.md)). For the sake of time, [MSC3401](https://github.com/matrix-org/matrix-doc/blob/matthew/group-voip/proposals/3401-group-voip.md) is integrated into the mainline applications as a widget, but sharing the host app's Matrix client, on all 3 platforms embedding Element Call.

Note the native integration MSC3401 is at the current point in time out of scope.

## Linked Issues
- [x]  implementation is done https://github.com/matrix-org/matrix-spec-proposals/pull/3819
- [x] https://github.com/matrix-org/matrix-js-sdk/issues/2552
- [x] https://github.com/vector-im/element-web/issues/22964
- [x] https://github.com/vector-im/element-call/issues/330
- [x] https://github.com/vector-im/element-call/issues/486
- [x] https://github.com/vector-im/element-call/issues/558
- [x] https://github.com/matrix-org/matrix-js-sdk/issues/2589
- [x] https://github.com/vector-im/element-web/issues/23107
- [x] https://github.com/vector-im/element-web/issues/23453
- [x] https://github.com/vector-im/element-web/issues/23335
- [x] https://github.com/vector-im/element-web/issues/23494
- [x] https://github.com/matrix-org/matrix-react-sdk/pull/9423
- [x] https://github.com/matrix-org/matrix-react-sdk/pull/9424
- [x] https://github.com/matrix-org/matrix-react-sdk/pull/9426
- [x] https://github.com/vector-im/element-web/issues/23335
