### ISSUE TITLE
Call debug information & Telemetry (in a machine readable way)

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#915]
## Highlevel overview

We have failures on both full mesh and focus based Element Call that are hard to debug. Any debugging we can do involves manually lining up and trawling through logs from each client and (if applicable) the SFU. This is not really a sustainable solution and it is critical to the success of MatrixRTC and Element Call that we can diagnose and fix failure modes. 

Therefore, alongside the above change, we add feedback and debugging, investigating OpenTelemetry to collect call events and logs from all parties (on our own deployments and where permission is granted) in one place.

We need this information on both sides: frontend and backend. Information to report are:
- WebRTC signaling (ICE candidates, tracks advertising/requesting, feeds we have, transceiver directions, basically a dump of the SDP)
- business logic signaling (mute states, requesting media layers)
- also address KPIs
  - video frozen 
  - audio drop outs
  - total bandwidth used

Level of detail:
- global debug view
- zoom into participants

```[tasklist]
### Linked Issues
- [x] Investigate OpenTelemetry with a goal to report (not necessarily all initially)
- [x] Error events from calls
- [x] Error events from group calls
- [x] Undecryptable to-device events
- [x] Incoming to-device events
- [ ] https://github.com/vector-im/element-call/issues/959
- [ ] https://github.com/vector-im/element-call/issues/950
- [ ] https://github.com/matrix-org/waterfall/issues/141
- [ ] https://github.com/vector-im/element-call/issues/948
- [ ] https://github.com/vector-im/element-call/issues/949
- [ ] https://github.com/vector-im/element-call/issues/947
- [x] https://github.com/vector-im/voip-internal/issues/131
```

```[tasklist]
## Goals
- [x] We should already know when somebody has been able to see/hear someone on a call (assuming they have granted permission for debugging) without them rageshaking / coming to tell us
- [x] Add OpenTelemetry spans to rage-shakes and provide a compelling analysis framework
```

## Relation to other Epics
- https://github.com/vector-im/element-call/issues/533
